create table if not exists public.folders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 32),
  created_at timestamptz not null default now(),
  constraint folders_id_user_id_key unique (id, user_id)
);

create unique index if not exists folders_user_name_unique
  on public.folders (user_id, lower(name));

create table if not exists public.bookmark (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title varchar not null,
  type varchar not null check (type in ('Link', 'Code', 'Note')),
  folder varchar,
  url varchar not null default '',
  note varchar not null default '',
  tags json not null default '[]'::json
);

alter table public.bookmark
  add column if not exists url varchar not null default '';

alter table public.folders enable row level security;
alter table public.bookmark enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.folders, public.bookmark to authenticated;
grant usage, select on sequence public.bookmark_id_seq to authenticated;

drop policy if exists "Users can manage their own folders" on public.folders;
create policy "Users can manage their own folders"
  on public.folders for all
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can manage shared bookmarks" on public.bookmark;
create policy "Authenticated users can manage shared bookmarks"
  on public.bookmark for all to authenticated
  using (true)
  with check (true);
